<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BrandsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('brands')->delete();
        
        \DB::table('brands')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Bailleul',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Atlantis nature',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Aderma',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Arkopharma',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.45,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-31 15:27:15',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Cooper by roches',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.5,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-31 15:28:24',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Bioderma',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 23:03:15',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Klorane',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Mam',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Genevrier',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Pierre Fabre Healthcare',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Upsa by roches',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 4,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Guigoz',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Bausch et Lomb',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.45,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-31 15:09:25',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Nuxe',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Procter et Gamble',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Nutergia',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.2,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-31 15:29:56',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Santé verte',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Grimberg by St Jean',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-28 11:26:28',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Hra Cicatridine by St Jean',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Pranarom',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Nutravalia Anaka3 Luxeol',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Pierre Fabre OralCare',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Filorga',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Mayoli probiolog',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Mayoli Euphon',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 2,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Johnson Johnson',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Lehning',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Svr',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Yogi Tea',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Cavailles',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Hra Compeed',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Hra Cicatridine by Bosquet',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Imelda Pediakid',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Pic',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Weleda',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Densmore Saveal',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 3,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Gaba',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 6,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Pileje',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 6,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Synergia D Stress',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 6,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Quies',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 6,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Melisana',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 6,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Caudalie',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Bouchara',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Cosmediet',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Ea Granions Eafit',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Codifra',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Cooper by Ferriere',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Sunstar Gum',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Upsa',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Panda Tea',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 5,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Grinberg by Technolpole ',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 7,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Ulabs Fluocaril',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 7,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Gsk',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 7,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Auvex Biocanina Leuro Biotsim',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 10,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Bayer',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 10,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Biocodex',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 10,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Iprat',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 10,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Pediact',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 10,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Alfadiab Diabfine',
                'contact_email' => NULL,
                'contact_phone' => NULL,
                'contact_name' => NULL,
                'discount' => 0.0,
                'manager_id' => 8,
                'comment' => NULL,
                'created_at' => '2022-07-21 16:09:30',
                'updated_at' => '2022-07-21 16:09:30',
            ),
        ));
        
        
    }
}