<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrderTemplateContentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('order_template_contents')->delete();
        
        \DB::table('order_template_contents')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ean' => '12214X667',
                'ordertemplate_id' => 1,
                'name' => 'Prodigieux Huile de douche',
                'variant' => '200 ml',
                'price' => '5.0000',
                'discount' => '0.0100',
                'step_price' => '4.1000',
                'step_value' => 50,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale fin de série',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ean' => '12214X669',
                'ordertemplate_id' => 1,
                'name' => 'Lait fraîcheur après-soleil visage et corp',
                'variant' => '200ml',
                'price' => '8.5000',
                'discount' => '0.0100',
                'step_price' => '6.0500',
                'step_value' => 100,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'ean' => '12214X668',
                'ordertemplate_id' => 1,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ml',
                'price' => '14.0000',
                'discount' => '0.0100',
                'step_price' => '10.5000',
                'step_value' => 100,
                'package_qty' => 30,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ean' => '12214X670',
                'ordertemplate_id' => 1,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ML',
                'price' => '25.0000',
                'discount' => '0.0100',
                'step_price' => '20.3000',
                'step_value' => 80,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'ean' => '12214X671',
                'ordertemplate_id' => 1,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '100ML',
                'price' => '50.0000',
                'discount' => '0.0100',
                'step_price' => '35.3000',
                'step_value' => 40,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'ean' => '12214X667',
                'ordertemplate_id' => 3,
                'name' => 'Prodigieux Huile de douche',
                'variant' => '200 ml',
                'price' => '5.0000',
                'discount' => '0.0100',
                'step_price' => '4.1000',
                'step_value' => 50,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale fin de série',
                'created_at' => '2022-07-21 15:28:40',
                'updated_at' => '2022-07-21 15:28:40',
            ),
            6 => 
            array (
                'id' => 7,
                'ean' => '12214X669',
                'ordertemplate_id' => 3,
                'name' => 'Lait fraîcheur après-soleil visage et corp',
                'variant' => '200ml',
                'price' => '8.5000',
                'discount' => '0.0100',
                'step_price' => '6.0500',
                'step_value' => 100,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => '2022-07-21 15:28:40',
                'updated_at' => '2022-07-21 15:28:40',
            ),
            7 => 
            array (
                'id' => 8,
                'ean' => '12214X668',
                'ordertemplate_id' => 3,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ml',
                'price' => '14.0000',
                'discount' => '0.0100',
                'step_price' => '10.5000',
                'step_value' => 100,
                'package_qty' => 30,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => '2022-07-21 15:28:40',
                'updated_at' => '2022-07-21 15:28:40',
            ),
            8 => 
            array (
                'id' => 9,
                'ean' => '12214X670',
                'ordertemplate_id' => 3,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ML',
                'price' => '25.0000',
                'discount' => '0.0100',
                'step_price' => '20.3000',
                'step_value' => 80,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => '2022-07-21 15:28:40',
                'updated_at' => '2022-07-21 15:28:40',
            ),
            9 => 
            array (
                'id' => 10,
                'ean' => '12214X671',
                'ordertemplate_id' => 3,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '100ML',
                'price' => '50.0000',
                'discount' => '0.0100',
                'step_price' => '35.3000',
                'step_value' => 40,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => '2022-07-21 15:28:40',
                'updated_at' => '2022-07-21 15:28:40',
            ),
            10 => 
            array (
                'id' => 16,
                'ean' => '3400934691638',
                'ordertemplate_id' => 7,
                'name' => 'ALLERGIFLASH 10 UNIDOSES',
                'variant' => NULL,
                'price' => '7.2500',
                'discount' => '0.4500',
                'step_price' => '7.2500',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:18:14',
                'updated_at' => '2022-07-27 14:49:08',
            ),
            11 => 
            array (
                'id' => 17,
                'ean' => '3400930145944',
                'ordertemplate_id' => 7,
                'name' => 'ALLERGIFLASH flacon',
                'variant' => NULL,
                'price' => '7.2500',
                'discount' => '0.4500',
                'step_price' => '7.2500',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:25:53',
                'updated_at' => '2022-07-27 14:49:24',
            ),
            12 => 
            array (
                'id' => 18,
                'ean' => '3614790000453',
                'ordertemplate_id' => 7,
                'name' => 'aqualarm 20 unidoses',
                'variant' => NULL,
                'price' => '6.4000',
                'discount' => '0.4500',
                'step_price' => '6.4000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:28:34',
                'updated_at' => '2022-07-27 14:48:30',
            ),
            13 => 
            array (
                'id' => 19,
                'ean' => '3614790000583',
                'ordertemplate_id' => 7,
                'name' => 'AQUALARM UP flac 10ml',
                'variant' => NULL,
                'price' => '5.9500',
                'discount' => '0.4500',
                'step_price' => '5.9500',
                'step_value' => 1,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:29:41',
                'updated_at' => '2022-07-27 14:50:58',
            ),
            14 => 
            array (
                'id' => 20,
                'ean' => '3614790000606',
                'ordertemplate_id' => 7,
                'name' => 'AQUALARM INTENSIVE flacon 10ml',
                'variant' => NULL,
                'price' => '8.9000',
                'discount' => '0.4500',
                'step_price' => '7.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:31:01',
                'updated_at' => '2022-07-27 14:50:46',
            ),
            15 => 
            array (
                'id' => 21,
                'ean' => '3614790000613',
                'ordertemplate_id' => 7,
                'name' => 'AQUALARM INTENSIVE spray 10ml',
                'variant' => NULL,
                'price' => '12.9000',
                'discount' => '0.4500',
                'step_price' => '12.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:32:36',
                'updated_at' => '2022-07-27 14:49:40',
            ),
            16 => 
            array (
                'id' => 22,
                'ean' => '3614790000088',
                'ordertemplate_id' => 7,
                'name' => 'AQUALARM TRIPLE ACTION 10ml',
                'variant' => NULL,
                'price' => '11.6000',
                'discount' => '0.4500',
                'step_price' => '11.6000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:35:15',
                'updated_at' => '2022-07-27 14:49:53',
            ),
            17 => 
            array (
                'id' => 23,
                'ean' => '3614790000347',
                'ordertemplate_id' => 7,
                'name' => 'BLOXALLERGY flacon 10ml',
                'variant' => NULL,
                'price' => '7.9000',
                'discount' => '0.4500',
                'step_price' => '7.9000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:36:47',
                'updated_at' => '2022-07-27 14:52:23',
            ),
            18 => 
            array (
                'id' => 24,
                'ean' => '3614790000224',
                'ordertemplate_id' => 7,
                'name' => 'BLOXALLERGY 20 dosettes',
                'variant' => NULL,
                'price' => '7.9000',
                'discount' => '0.4500',
                'step_price' => '7.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:38:13',
                'updated_at' => '2022-07-27 14:50:33',
            ),
            19 => 
            array (
                'id' => 25,
                'ean' => '3614790000767',
                'ordertemplate_id' => 7,
                'name' => 'BLOXALLERGY spray 10ml',
                'variant' => NULL,
                'price' => '12.9000',
                'discount' => '0.4500',
                'step_price' => '12.9000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:39:07',
                'updated_at' => '2022-07-27 14:50:20',
            ),
            20 => 
            array (
                'id' => 26,
                'ean' => '3400930093832',
                'ordertemplate_id' => 7,
                'name' => 'DESOMEDINE flacon 10ml',
                'variant' => NULL,
                'price' => '5.9000',
                'discount' => '0.4500',
                'step_price' => '5.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:40:02',
                'updated_at' => '2022-07-27 14:51:26',
            ),
            21 => 
            array (
                'id' => 27,
                'ean' => '3400934867996',
                'ordertemplate_id' => 7,
                'name' => 'DESOMEDINE 10 unidoses',
                'variant' => NULL,
                'price' => '5.9000',
                'discount' => '0.4500',
                'step_price' => '5.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:41:01',
                'updated_at' => '2022-07-27 14:51:38',
            ),
            22 => 
            array (
                'id' => 28,
                'ean' => '3614790000699',
                'ordertemplate_id' => 7,
                'name' => 'DESODROP flacon 8ml',
                'variant' => NULL,
                'price' => '9.9000',
                'discount' => '0.4500',
                'step_price' => '9.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:41:59',
                'updated_at' => '2022-07-27 14:51:13',
            ),
            23 => 
            array (
                'id' => 29,
                'ean' => '4029835000050',
                'ordertemplate_id' => 7,
                'name' => 'DEXPANTHENOL 10gr',
                'variant' => NULL,
                'price' => '5.7000',
                'discount' => '0.4500',
                'step_price' => '5.7000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:42:59',
                'updated_at' => '2022-07-27 14:50:07',
            ),
            24 => 
            array (
                'id' => 30,
                'ean' => '3400935356703',
                'ordertemplate_id' => 7,
                'name' => 'OPHTACALM 10 unidoses',
                'variant' => NULL,
                'price' => '5.8000',
                'discount' => '0.4500',
                'step_price' => '5.8000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:43:57',
                'updated_at' => '2022-07-27 14:51:52',
            ),
            25 => 
            array (
                'id' => 31,
                'ean' => '3400934692178',
                'ordertemplate_id' => 7,
                'name' => 'OPHTACALM flacon 10ml',
                'variant' => NULL,
                'price' => '6.3500',
                'discount' => '0.4500',
                'step_price' => '6.3500',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:44:48',
                'updated_at' => '2022-07-27 14:52:08',
            ),
            26 => 
            array (
                'id' => 32,
                'ean' => '3614790000620',
                'ordertemplate_id' => 7,
                'name' => 'OPHTAXIA flacon 100ml',
                'variant' => NULL,
                'price' => '5.6000',
                'discount' => '0.4500',
                'step_price' => '3.0800',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:45:58',
                'updated_at' => '2022-07-27 14:45:58',
            ),
            27 => 
            array (
                'id' => 33,
                'ean' => '3401053843182',
                'ordertemplate_id' => 7,
                'name' => 'OPHTAXIA 10 unidoses',
                'variant' => NULL,
                'price' => '3.9500',
                'discount' => '0.4500',
                'step_price' => '2.1725',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:46:55',
                'updated_at' => '2022-07-27 14:46:55',
            ),
            28 => 
            array (
                'id' => 34,
                'ean' => '3401060024185',
                'ordertemplate_id' => 7,
                'name' => 'OPHTAXIA 20 lingettes',
                'variant' => NULL,
                'price' => '9.6000',
                'discount' => '0.4500',
                'step_price' => '9.6000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:53:32',
                'updated_at' => '2022-07-27 14:53:32',
            ),
            29 => 
            array (
                'id' => 35,
                'ean' => '3614790000385',
                'ordertemplate_id' => 7,
                'name' => 'SENSIOPTIC spray 10ml',
                'variant' => NULL,
                'price' => '12.5000',
                'discount' => '0.4500',
                'step_price' => '12.5000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:54:16',
                'updated_at' => '2022-07-27 14:54:16',
            ),
            30 => 
            array (
                'id' => 36,
                'ean' => '3614790000378',
                'ordertemplate_id' => 7,
                'name' => 'SENSIOPTIC flacon 10ml',
                'variant' => NULL,
                'price' => '8.5000',
                'discount' => '0.4500',
                'step_price' => '8.5000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:55:01',
                'updated_at' => '2022-07-27 14:55:01',
            ),
            31 => 
            array (
                'id' => 37,
                'ean' => '3400934587160',
                'ordertemplate_id' => 7,
                'name' => 'SENSIVISION 10 unidoses',
                'variant' => NULL,
                'price' => '5.9000',
                'discount' => '0.4500',
                'step_price' => '5.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:55:57',
                'updated_at' => '2022-07-27 14:55:57',
            ),
            32 => 
            array (
                'id' => 38,
                'ean' => '3401595198504',
                'ordertemplate_id' => 7,
                'name' => 'SENSIVISION flacon 10ml',
                'variant' => NULL,
                'price' => '5.9000',
                'discount' => '0.4500',
                'step_price' => '5.9000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:56:50',
                'updated_at' => '2022-07-27 14:56:50',
            ),
            33 => 
            array (
                'id' => 39,
                'ean' => '340159198504',
                'ordertemplate_id' => 7,
                'name' => 'VIDISAN flacon 10ml',
                'variant' => NULL,
                'price' => '5.9000',
                'discount' => '0.4500',
                'step_price' => '5.9000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:57:56',
                'updated_at' => '2022-07-27 14:57:56',
            ),
            34 => 
            array (
                'id' => 40,
                'ean' => '4260196620024',
                'ordertemplate_id' => 7,
                'name' => 'VIDISAN 10 unidoses',
                'variant' => NULL,
                'price' => '5.9000',
                'discount' => '0.4500',
                'step_price' => '5.9000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 14:58:47',
                'updated_at' => '2022-07-27 14:58:47',
            ),
            35 => 
            array (
                'id' => 41,
                'ean' => '3400936730182',
                'ordertemplate_id' => 7,
                'name' => 'VITAMINE B12 10 unidoses',
                'variant' => NULL,
                'price' => '5.2000',
                'discount' => '0.4500',
                'step_price' => '5.2000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:00:06',
                'updated_at' => '2022-07-27 15:00:06',
            ),
            36 => 
            array (
                'id' => 42,
                'ean' => '3400936730182',
                'ordertemplate_id' => 7,
                'name' => 'VITAMINE B12 10 unidoses',
                'variant' => NULL,
                'price' => '5.2000',
                'discount' => '0.4500',
                'step_price' => '5.2000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:00:22',
                'updated_at' => '2022-07-27 15:00:22',
            ),
            37 => 
            array (
                'id' => 43,
                'ean' => '3614790000057',
                'ordertemplate_id' => 7,
                'name' => 'BLOXANG éponges',
                'variant' => NULL,
                'price' => '6.7000',
                'discount' => '0.4500',
                'step_price' => '6.7000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:01:28',
                'updated_at' => '2022-07-27 15:01:28',
            ),
            38 => 
            array (
                'id' => 44,
                'ean' => '3401051621676',
                'ordertemplate_id' => 7,
                'name' => 'BLOXANG topic 30gr',
                'variant' => NULL,
                'price' => '6.3000',
                'discount' => '0.4500',
                'step_price' => '6.3000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:02:16',
                'updated_at' => '2022-07-27 15:02:16',
            ),
            39 => 
            array (
                'id' => 45,
                'ean' => '4049649000732',
                'ordertemplate_id' => 7,
                'name' => 'BLOXRHUME spray nasal',
                'variant' => NULL,
                'price' => '6.4000',
                'discount' => '0.4500',
                'step_price' => '6.4000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:03:00',
                'updated_at' => '2022-07-27 15:03:00',
            ),
            40 => 
            array (
                'id' => 46,
                'ean' => '3401051621218',
                'ordertemplate_id' => 7,
                'name' => 'BLOXINUS spray nasal',
                'variant' => NULL,
                'price' => '11.7000',
                'discount' => '0.4500',
                'step_price' => '11.7000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:04:04',
                'updated_at' => '2022-07-27 15:04:04',
            ),
            41 => 
            array (
                'id' => 47,
                'ean' => '3614790000026',
                'ordertemplate_id' => 7,
                'name' => 'BLOXAPHTE bain bouche 100ml',
                'variant' => NULL,
                'price' => '8.5000',
                'discount' => '0.4500',
                'step_price' => '8.5000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:06:33',
                'updated_at' => '2022-07-27 15:06:33',
            ),
            42 => 
            array (
                'id' => 48,
                'ean' => '3614790000033',
                'ordertemplate_id' => 7,
                'name' => 'BLOXAPHTE spray adulte 20ml',
                'variant' => NULL,
                'price' => '8.5000',
                'discount' => '0.4500',
                'step_price' => '8.5000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:07:38',
                'updated_at' => '2022-07-27 15:07:38',
            ),
            43 => 
            array (
                'id' => 49,
                'ean' => '3614790000019',
                'ordertemplate_id' => 7,
                'name' => 'BLOXAPHTE gel junior 15ml',
                'variant' => NULL,
                'price' => '8.5000',
                'discount' => '0.4500',
                'step_price' => '8.5000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:08:37',
                'updated_at' => '2022-07-27 15:08:37',
            ),
            44 => 
            array (
                'id' => 50,
                'ean' => '3614790000002',
                'ordertemplate_id' => 7,
                'name' => 'BLOXAPHTE gel adulte 15ml',
                'variant' => NULL,
                'price' => '8.5000',
                'discount' => '0.4500',
                'step_price' => '8.5000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:09:32',
                'updated_at' => '2022-07-27 15:09:32',
            ),
            45 => 
            array (
                'id' => 51,
                'ean' => '4049649000749',
                'ordertemplate_id' => 7,
                'name' => 'BLOXOTO gouttes auric flacon 15ml',
                'variant' => NULL,
                'price' => '6.4000',
                'discount' => '0.4500',
                'step_price' => '6.4000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:10:30',
                'updated_at' => '2022-07-27 15:10:30',
            ),
            46 => 
            array (
                'id' => 52,
                'ean' => '3614790000729',
                'ordertemplate_id' => 7,
                'name' => 'CERUALGIE gouttes auriculaires',
                'variant' => NULL,
                'price' => '5.2000',
                'discount' => '0.4500',
                'step_price' => '5.2000',
                'step_value' => 10,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:11:29',
                'updated_at' => '2022-07-27 15:11:29',
            ),
            47 => 
            array (
                'id' => 53,
                'ean' => '3401577348347',
                'ordertemplate_id' => 7,
                'name' => 'CERUSPRAY',
                'variant' => NULL,
                'price' => '6.8000',
                'discount' => '0.4500',
                'step_price' => '6.8000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:12:07',
                'updated_at' => '2022-07-27 15:12:07',
            ),
            48 => 
            array (
                'id' => 54,
                'ean' => '3614790000750',
                'ordertemplate_id' => 7,
                'name' => 'CERUBABY solution auric 15ml',
                'variant' => 'uriculaire',
                'price' => '5.5000',
                'discount' => '0.4500',
                'step_price' => '5.5000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:13:06',
                'updated_at' => '2022-07-27 15:13:06',
            ),
            49 => 
            array (
                'id' => 55,
                'ean' => '3614790000705',
                'ordertemplate_id' => 7,
                'name' => 'CERUCALM solution auric 15ml',
                'variant' => NULL,
                'price' => '6.4000',
                'discount' => '0.4500',
                'step_price' => '6.4000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:13:44',
                'updated_at' => '2022-07-27 15:13:44',
            ),
            50 => 
            array (
                'id' => 56,
                'ean' => '3614790000743',
                'ordertemplate_id' => 7,
                'name' => 'CERUDROP solution auric 12ml',
                'variant' => NULL,
                'price' => '6.2000',
                'discount' => '0.4500',
                'step_price' => '6.2000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:14:28',
                'updated_at' => '2022-07-27 15:14:28',
            ),
            51 => 
            array (
                'id' => 57,
                'ean' => '3400933998301',
                'ordertemplate_id' => 7,
                'name' => 'CROMORHINOL spray nasal 15ml',
                'variant' => NULL,
                'price' => '6.7500',
                'discount' => '0.4500',
                'step_price' => '6.7500',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:15:23',
                'updated_at' => '2022-07-27 15:15:23',
            ),
            52 => 
            array (
                'id' => 58,
                'ean' => '3400933445621',
                'ordertemplate_id' => 7,
                'name' => 'DESOMEDINE spray nasal 10ml',
                'variant' => NULL,
                'price' => '5.4000',
                'discount' => '0.4500',
                'step_price' => '5.4000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:16:11',
                'updated_at' => '2022-07-27 15:16:11',
            ),
            53 => 
            array (
                'id' => 59,
                'ean' => '4030571006404',
                'ordertemplate_id' => 7,
                'name' => 'HYARHINOL spray nasal 15ml',
                'variant' => NULL,
                'price' => '7.4000',
                'discount' => '0.4500',
                'step_price' => '7.4000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:16:57',
                'updated_at' => '2022-07-27 15:16:57',
            ),
            54 => 
            array (
                'id' => 60,
                'ean' => '3400930126332',
                'ordertemplate_id' => 7,
                'name' => 'LYSORYNX 36 pastilles',
                'variant' => NULL,
                'price' => '5.5000',
                'discount' => '0.4500',
                'step_price' => '5.5000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '<p>g&eacute;n&eacute;rique lysopaine</p>
<p>&nbsp;</p>',
                'created_at' => '2022-07-27 15:18:11',
                'updated_at' => '2022-07-27 15:18:11',
            ),
            55 => 
            array (
                'id' => 61,
                'ean' => '4049649000763',
                'ordertemplate_id' => 7,
            'name' => 'BLOXAIR solution buvable 20ml (gastro-entérologie)',
                'variant' => NULL,
                'price' => '7.1000',
                'discount' => '0.4500',
                'step_price' => '7.1000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:19:22',
                'updated_at' => '2022-07-27 15:19:22',
            ),
            56 => 
            array (
                'id' => 62,
                'ean' => '3401561747293',
                'ordertemplate_id' => 7,
                'name' => 'MYOD\'contact 30 gélules',
                'variant' => NULL,
                'price' => '9.4000',
                'discount' => '0.4500',
                'step_price' => '9.4000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:20:21',
                'updated_at' => '2022-07-27 15:20:21',
            ),
            57 => 
            array (
                'id' => 63,
                'ean' => '3401581591487',
                'ordertemplate_id' => 7,
                'name' => 'C\'ZEN états nauséeux 30cps',
                'variant' => NULL,
                'price' => '7.2000',
                'discount' => '0.4500',
                'step_price' => '7.2000',
                'step_value' => 14,
                'package_qty' => 14,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:21:17',
                'updated_at' => '2022-07-27 15:21:17',
            ),
            58 => 
            array (
                'id' => 64,
                'ean' => '3401528548581',
                'ordertemplate_id' => 7,
                'name' => 'C\'ZEN NUIT 30cps',
                'variant' => NULL,
                'price' => '8.5000',
                'discount' => '0.4500',
                'step_price' => '8.5000',
                'step_value' => 12,
                'package_qty' => 12,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 15:22:03',
                'updated_at' => '2022-07-27 15:22:03',
            ),
            59 => 
            array (
                'id' => 65,
                'ean' => '0850803002622',
                'ordertemplate_id' => 7,
                'name' => 'THERA PERL MULTIZONES',
                'variant' => NULL,
                'price' => '7.8000',
                'discount' => '0.4500',
                'step_price' => '7.8000',
                'step_value' => 3,
                'package_qty' => 3,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 18:29:18',
                'updated_at' => '2022-07-27 18:29:18',
            ),
            60 => 
            array (
                'id' => 66,
                'ean' => '0850803002769',
                'ordertemplate_id' => 7,
                'name' => 'THERA PEARL ARTICULATIONS',
                'variant' => NULL,
                'price' => '10.5000',
                'discount' => '0.4500',
                'step_price' => '10.5000',
                'step_value' => 3,
                'package_qty' => 3,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 18:30:12',
                'updated_at' => '2022-07-27 18:30:12',
            ),
            61 => 
            array (
                'id' => 67,
                'ean' => '0850803002721',
                'ordertemplate_id' => 7,
                'name' => 'THERA PEARL DOS',
                'variant' => NULL,
                'price' => '16.8000',
                'discount' => '0.4500',
                'step_price' => '16.8000',
                'step_value' => 3,
                'package_qty' => 3,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => NULL,
                'created_at' => '2022-07-27 18:30:49',
                'updated_at' => '2022-07-27 18:30:49',
            ),
        ));
        
        
    }
}