<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrderTemplateContentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('order_template_contents')->delete();
        
        \DB::table('order_template_contents')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ean' => '12214X667',
                'ordertemplate_id' => 1,
                'name' => 'Prodigieux Huile de douche',
                'variant' => '200 ml',
                'price' => '5.0000',
                'discount' => '0.0100',
                'step_price' => '4.1000',
                'step_value' => 50,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale fin de série',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ean' => '12214X669',
                'ordertemplate_id' => 1,
                'name' => 'Lait fraîcheur après-soleil visage et corp',
                'variant' => '200ml',
                'price' => '8.5000',
                'discount' => '0.0100',
                'step_price' => '6.0500',
                'step_value' => 100,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'ean' => '12214X668',
                'ordertemplate_id' => 1,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ml',
                'price' => '14.0000',
                'discount' => '0.0100',
                'step_price' => '10.5000',
                'step_value' => 100,
                'package_qty' => 30,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ean' => '12214X670',
                'ordertemplate_id' => 1,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ML',
                'price' => '25.0000',
                'discount' => '0.0100',
                'step_price' => '20.3000',
                'step_value' => 80,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'ean' => '12214X671',
                'ordertemplate_id' => 1,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '100ML',
                'price' => '50.0000',
                'discount' => '0.0100',
                'step_price' => '35.3000',
                'step_value' => 40,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'ean' => '12214X667',
                'ordertemplate_id' => 3,
                'name' => 'Prodigieux Huile de douche',
                'variant' => '200 ml',
                'price' => '5.0000',
                'discount' => '0.0100',
                'step_price' => '4.1000',
                'step_value' => 50,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale fin de série',
                'created_at' => '2022-07-21 14:28:40',
                'updated_at' => '2022-07-21 14:28:40',
            ),
            6 => 
            array (
                'id' => 7,
                'ean' => '12214X669',
                'ordertemplate_id' => 3,
                'name' => 'Lait fraîcheur après-soleil visage et corp',
                'variant' => '200ml',
                'price' => '8.5000',
                'discount' => '0.0100',
                'step_price' => '6.0500',
                'step_value' => 100,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => '2022-07-21 14:28:40',
                'updated_at' => '2022-07-21 14:28:40',
            ),
            7 => 
            array (
                'id' => 8,
                'ean' => '12214X668',
                'ordertemplate_id' => 3,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ml',
                'price' => '14.0000',
                'discount' => '0.0100',
                'step_price' => '10.5000',
                'step_value' => 100,
                'package_qty' => 30,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => 'promo spéciale été',
                'created_at' => '2022-07-21 14:28:40',
                'updated_at' => '2022-07-21 14:28:40',
            ),
            8 => 
            array (
                'id' => 9,
                'ean' => '12214X670',
                'ordertemplate_id' => 3,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '50ML',
                'price' => '25.0000',
                'discount' => '0.0100',
                'step_price' => '20.3000',
                'step_value' => 80,
                'package_qty' => 20,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => '2022-07-21 14:28:40',
                'updated_at' => '2022-07-21 14:28:40',
            ),
            9 => 
            array (
                'id' => 10,
                'ean' => '12214X671',
                'ordertemplate_id' => 3,
                'name' => 'Baume Visage Ultra-Réconfortant, Rêve de Miel',
                'variant' => '100ML',
                'price' => '50.0000',
                'discount' => '0.0100',
                'step_price' => '35.3000',
                'step_value' => 40,
                'package_qty' => 10,
                'demi_package' => 0,
                'multi_delivery' => 0,
                'free' => 0,
                'free_stp' => NULL,
                'free_qty' => NULL,
                'comment' => '',
                'created_at' => '2022-07-21 14:28:40',
                'updated_at' => '2022-07-21 14:28:40',
            ),
        ));
        
        
    }
}